### ISSUE TITLE
Terraform 0.11 and earlier required type constraints

### ISSUE THREAD

**Issue by sfaria1** [BorisLabs/terraform-aws-transfer#9]
╷
│ Error: Invalid quoted type constraints
│
│   on .terraform\modules\transfer\variables.tf line 13, in variable "tags":
│   13:   type    = "map"
│
│ Terraform 0.11 and earlier required type constraints to be given in quotes, but that form is now deprecated and will be removed in a future version of
│ Terraform. Remove the quotes around "map" and write map(string) instead to explicitly indicate that the map elements are strings.
╵

╷
│ Error: Invalid quoted type constraints
│
│   on .terraform\modules\transfer_server\variables.tf line 13, in variable "tags":
│   13:   type    = "map"
│
│ Terraform 0.11 and earlier required type constraints to be given in quotes, but that form is now deprecated and will be removed in a future version of
│ Terraform. Remove the quotes around "map" and write map(string) instead to explicitly indicate that the map elements are strings.
╵

╷
│ Error: Invalid quoted type constraints
│
│   on .terraform\modules\user\variables.tf line 13, in variable "tags":
│   13:   type    = "map"
│
│ Terraform 0.11 and earlier required type constraints to be given in quotes, but that form is now deprecated and will be removed in a future version of
│ Terraform. Remove the quotes around "map" and write map(string) instead to explicitly indicate that the map elements are strings.
╵

**Comment by sfaria1** [comment]
fixed this manually but this should be fixed in the repo

**Comment by JoshiiSinfield** [comment]
Hi @sfaria1 ,

Apologies for late reply. What version of the module are you using? That variable was updated from version 0.1.0. 

0.4.0 is the latest, please can you try with that?
